FROM node:14.17.6-alpine@sha256:d339c269a72f04c7ca6247eb09a0038f1927324c5c2518aeb8f37369a6560ead AS base

WORKDIR /app

COPY package.json .
COPY package-lock.json .

# for a more deterministic build use npm ci
RUN npm ci

COPY index.ts .
EXPOSE 8080

CMD ["sh"]
